<a href="https://colab.research.google.com/github/irfanghapar/Python-Programming/blob/main/NumPy_Arrays_Lab_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
# Exercise 1

import numpy as np
np.random.seed(21)
random_integers = np.random.randint(1, high = 500000, size = (20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [34]:
# Exercise 2

second_column = random_integers[:, 1]
average_second_column = np.mean(second_column)

print(f"Average second column: {average_second_column: .2f}")

Average second column:  214895.80


In [35]:
# Exercise 3

five_rows = random_integers[0:4, 2:3]
average_five_rows = np.mean(five_rows)

print(f"Average five rows: {average_five_rows}")

Average five rows: 245929.5


In [36]:
# Exercise 4

import numpy as np
first_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(first_matrix)

second_matrix = np.array([1,2,3])
print(second_matrix)

first_matrix + second_matrix

[[1 2 3]
 [4 5 6]]
[1 2 3]


array([[2, 4, 6],
       [5, 7, 9]])

In [37]:
# Exercise 5

my_vector = np.array([1, 2, 3, 4, 5, 6])
selection = my_vector % 2 == 0
my_vector[selection]

array([2, 4, 6])

Basic Slicing

In [39]:
# Exercise 6

import numpy as np
my_array = np.array([1, 2, 3, 4])
print(my_array)

my_slice = my_array[1:3]
print(my_slice)

my_slice[0] = -1
print(my_slice)

print(my_array)
print(my_array[1])

[1 2 3 4]
[2 3]
[-1  3]
[ 1 -1  3  4]
-1


One of the nuances of can can easily lead to problems is that when one
takes a slice of an array, one does not actually get a new array; rather, one is
given a “view” on the original array, meaning they are sharing the same
underlying data.

In [28]:
x = [1, 2, 3]
y = x[0:2]
y[0] = "a change"
y
x

[1, 2, 3]

Basic indexing. Why?

In contrast, fancy indexing involves using arrays (or lists) of indices to select elements or subarrays from another array, which is not what's happening in this case.

In [40]:
my_array = np.array([1, 2, 3])
my_slice = my_array[1:3]
my_slice[0] = -1
my_array

array([ 1, -1,  3])

Using fancy indexing = non contiguos selection, using an array of indices

In [41]:
my_array = np.array([1, 2, 3])
my_slice = my_array[[1,2]] #fancy indexing
my_slice[0] = -1
my_array


array([1, 2, 3])

modify a slice without using contiguous selection or not using an array of indices, you get a copy, so changes
won’t propagate:

In [42]:
my_array = np.array([1, 2, 3])
my_slice = my_array[1:3]
my_slice = my_slice * 2
print(my_slice)
print(my_array)

[4 6]
[1 2 3]


A full-array manipulation and preserve your view, always use
square brackets on the left side of the assignment operator (=)

In [43]:
my_array = np.array([1, 2, 3])
my_slice = my_array[1:3]
my_slice[:] = my_slice * 2
my_slice
my_array

array([1, 4, 6])

Basic Indexing, here we want to show change in original value does affect the view

In [44]:
# Exercise 7

my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)
my_slice = my_array[:, 1:3]
print(my_slice)

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [45]:
# Exercise 8

my_array = my_array * 2
print(my_array)
print(my_slice)

[[ 2  4  6]
 [ 8 10 12]]
[[2 3]
 [5 6]]


Copy method will not affect the underlying data

In [46]:
#Exercise 11

my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)

my_slice = my_array[:, 1:3].copy()
print(my_slice)

my_array[:, :] = my_array * 2
print(my_slice)
print(my_array)

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[[2 3]
 [5 6]]
[[ 2  4  6]
 [ 8 10 12]]


test if one array is a view
of another with the code. It does work sometimes

In [22]:
my_array = np.array([1, 2, 3])
my_slice = my_array[1:3]
my_slice.base is my_array

True

But not always

NOTE: since my_array now has only two elements ([2, 3]), slicing from index 1 to 3 effectively selects only the last element, which is 3

In [27]:
my_array = np.array([1, 2, 3])
my_array = my_array[1:4]
print(my_array)
my_slice = my_array[1:3]
print(my_slice.base is my_array)
print(my_slice)
print(my_array)

[2 3]
False
[3]
[2 3]


In [28]:
my_slice[0] = -1
my_array

array([ 2, -1])

In [29]:
my_slice.base is my_array.base

True